[versions]
kotlin = "2.0.0"
pluginPublish = "1.2.1"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlinMpp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}


[libraries]
